### ISSUE TITLE
❓ How to use local image? 

### ISSUE THREAD

**Issue by ansible42** [ishworkh/docker-image-artifact-download#7]
Would the idea then be to have a follow on job that uses that image?  

I have a fairly large number of steps after downloading the image but they need to all be run in the same running container.

**Comment by ishworkh** [comment]
Yes the idea is to have a job upload your image using [docker upload action](https://github.com/ishworkh/docker-image-artifact-upload) and have following job(s) download them with this action and use as needed.

**Comment by ishworkh** [comment]
Closing the issue. Plz file another issue if you have further concerns.
