### ISSUE TITLE
New release with nodejs16

### ISSUE THREAD

**Issue by anshbansal** [ishworkh/docker-image-artifact-download#8]
Hi @ishworkh 
Thanks for the wonderful plugin. 

I see that you have upgraded dependencies from nodejs12 to nodejs16 in https://github.com/ishworkh/docker-image-artifact-download/pull/6. Will you be making a `v2` release for this plugin?

**Comment by ishworkh** [comment]
Hi, no v2 will be released for the action. The dependencies upgrade did not have any major changes to the action, so they were released in the same v1 tag.

Plz file another issue if you have further concerns :)
